### ISSUE TITLE
Connect Tool : Keyerror

### ISSUE THREAD

**Issue by ponceta** [QGEP/qgepplugin#9]
Win x64, qgis 2.18.16 qgep-plugin v.0.7.4

I get a keyerror whenever trying to use the connect tool.

```
KeyError: 'identifier' 
Traceback (most recent call last):
  File "C:/Users/pulpoar/.qgis2/python/plugins\qgepplugin\tools\qgepmaptools.py", line 637, in canvasReleaseEvent
    self.connect_features(self.source_match, self.snapresult)
  File "C:/Users/pulpoar/.qgis2/python/plugins\qgepplugin\tools\qgepmaptools.py", line 717, in connect_features
    'identifier'],
KeyError: 'identifier'
```

Difficult to me to say if I'm doing it right or wrong, doc could be a bit more explicit about how it works :

http://qgep.github.io/docs/fr/user-guide/editing/connect_wastewater_network_elements.html

https://vimeo.com/171536774

**Comment by sjib** [comment]
The tool connects the object to the choosen element via the selected foreign key(s):
![ezglayer_metatables_013_16012017_213400](https://user-images.githubusercontent.com/1265865/35867744-de3419b6-0b5a-11e8-8b5f-eeb9629d479a.png)

**Comment by m-kuhn** [comment]
@sjib @ponceta is this still an issue?
I'd like to close this issue tracker instead of the one at QGEP/QGEP https://github.com/QGEP/qgep/issues since most issues are there already anyway.
If this is still open, can you migrate it over and close, if this is no longer an issue, can you close this?
Thank you.
